### PR TITLE
NPM Package

### PR DESCRIPTION
**Pull request by karllhughes**
- Moved files around to facilitate NPM package as described in #12 
- Added instructions to readme
- Added a changelog so we can track changes in future releases

### CODE REVIEW

**Comment by karllhughes** [comment]
This PR supercedes #13, so we can either close that one or merge this after

Also, I left out any details about how to release to NPM as I figured you would want to be the maintainer. LMK if there's anything else I can do for this PR.

**Comment by rosszurowski** [comment]
Nice! This looks great.

There's a few additional things I'd like to add before publishing it on npm (eg. throwing errors for invalid config format with the JS API too), but I'll merge this and add those extras in a separate PR.

As for publishing on npm, I think I can add you as a collaborator on npm so we can both publish. I'll dig around and report back. I assume you're [~karllhughes](https://www.npmjs.com/~karllhughes) on npm too?

I closed #13 since this PR does the same work.

**Comment by karllhughes** [comment]
Yep, that's me.

Sounds good. I like where this is going!

**Comment by rosszurowski** [comment]
With this and #15 merged, the package felt good to publish to npm. It's now live at [micro-airtable-api](https://www.npmjs.com/package/micro-airtable-api). I sent an invite to you to be a collaborator on the npm package too, so you should have publish access.

With this, I think we've closed #12.

**Pull request merged**
